variable "group_id" {
  description = "Group number"
  type        = number
  default     = 6
}

variable "image_name" {
  description = "Docker image reference used by the group"
  type        = string
  default     = "g06-software-incident-triage:local"
}

variable "docker_host" {
  description = "Docker daemon endpoint"
  type        = string
  default     = "npipe:////./pipe/docker_engine"
}

variable "llm_base_url" {
  description = "LM Studio OpenAI-compatible API endpoint"
  type        = string
  default     = "http://host.docker.internal:1234/v1"
}

variable "llm_model" {
  description = "LM Studio model identifier"
  type        = string
  default     = "google/gemma-4-e4b"
}

variable "llm_timeout" {
  description = "Maximum inference time in seconds"
  type        = number
  default     = 90
}

variable "llm_max_tokens" {
  description = "Maximum number of tokens generated by the model"
  type        = number
  default     = 300
}